### ISSUE TITLE
Add a license file?

### ISSUE THREAD

**Issue by cjwirth** [shu223/AnimatedTransitionGallery#5]
Would you mind providing a license file?
Or at the very least, make some sort of indication of what you would like to use as the license? Many iOS libraries use either [MIT] or [Apache License v2]

[MIT]: http://opensource.org/licenses/MIT
[Apache License v2]: http://www.apache.org/licenses/LICENSE-2.0

**Comment by getaaron** [comment]
:thought_balloon: :+1:

**Comment by thedp** [comment]
+1
This is a great lib, but without a license no one will touch it.

**Comment by shu223** [comment]
The license for this repository conforms to each license of the repositories which are added as "submodule".

- https://github.com/shu223/AnimatedTransitionGallery/tree/master/submodules


For example, you can check the license of ADxxxxTransition classes here:

- https://github.com/applidium/ADTransitionController/blob/master/LICENSE
