### ISSUE TITLE
下载的Demo里边都是空的。

### ISSUE THREAD

**Issue by jinxiansen** [shu223/AnimatedTransitionGallery#8]
啊。
<img width="301" alt="e20539e9-a702-4706-8c85-ea79b1d56563" src="https://cloud.githubusercontent.com/assets/16829428/14550225/66a7d006-02f9-11e6-9ee6-7b99751692a7.png">

**Comment by shu223** [comment]
Please read README.

**Comment by jinxiansen** [comment]
看不懂哟，大先生。

**Comment by longhongwei17** [comment]
是卖书的？

**Comment by shu223** [comment]
Sorry, I can't understand Chinese :sob:

**Comment by shu223** [comment]
The problem will be resolved just read the README, so I close this issue.
